### ISSUE TITLE
Create wrapper script that spawns adam pipeline jobs from manifest

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#101]
Given a bucket with a manifest of FASTQ's that are arranged as we expect, we should be able to run the BWA/ADAM/HC pipeline on all those files. Alternatively, we should be able to run the pipeline + the GATK pipeline on a subset of these samples.

@hannes-ucsc can you add @jpdna to the BD2K org? He should be the assignee.

**Comment by hannes-ucsc** [comment]
@jpdna was invited.

**Comment by jpdna** [comment]
I should be assigned to this issue

**Comment by hannes-ucsc** [comment]
@jpdna It looks like you have yet to accept the invitation into the BD2KGenomic organization. Only then can I assign tickets to you.

**Comment by hannes-ucsc** [comment]
This should be a Toil script that iterates over the list of samples in the input list and creates one child job per sample. The child job function(s) should be imported from the relevant user modules here in toil-scripts.

Note that with the current AWS jobstore implementation, a simple loop would take too long. It has to be done recursively: If the input list is 10 samples, spawn concrete pipeline children each one of them. Otherwise, partition the list into 10 sublists and add a child with the current function for each of the sublists.
