### ISSUE TITLE
Create Überscript for ADAM/Toil test

### ISSUE THREAD

**Issue by almussel** [BD2KGenomics/toil-scripts#102]
- Wrap cgcloud create
- Metric collection process
- Launch all-samples toil script (either ADAM or GATK)

**Comment by hannes-ucsc** [comment]
Auto-scaling may be another responibility of the über-script: @hannes-ucsc in an email thread:

> Regarding growing a cluster in the spot market: there is literally no guarantee for how long a spot instance will be up for. So simply requesting eight spot instances per sample, waiting until they are provisioned and then proceeding would not be sufficient. You may block for a long time and once the eighth instance was provisioned, the first one may be shutting down already. 

> You constantly need to watch the cluster size and top it up with new instances as time goes by. We could split this up: a job in the multi-sample toil script could atomically update a shared variable containing the desired cluster size, let's say as an object in S3 (yes, eventual consistency is a problem but we have ways to make it work) or table row in SimpleDB. The über-script would monitor that value and tend to the actual cluster size accordingly. The beauty of this is that the pricing and placement decision is made centrally, allowing for more informed and complex bidding heuristics.

**Comment by hannes-ucsc** [comment]
During scrum we agreed to go with the above approach.

Note that there is an important strategy for spot bidding that we need to implement in cgcloud:

https://github.com/BD2KGenomics/cgcloud/issues/101

**Comment by hannes-ucsc** [comment]
Trying to formalize the autoscaling algo here. @almussel, this is modified from what we agreed to yesterday.

The central data structure is a mapping that maps a sample ID to the number of nodes currently needed for that sample. We assume that the data structure is persistent, can be updated atomically, and with strong consistency and is shared among all Toil workers as well as the head node that's running the überscript. To synchronize updates to that data structure, optimistic locking could be used (aka conditional updates). A single row in a SimpleDB domain fits those requirements.

A sample-specific job that adds one or more children occupying entire nodes modifies the mapping by atomically adding the required number of nodes in the entry for the current sample. The invariant is that the sum of all values in the mapping is the desired overall cluster size.

The überscript monitors the mapping and periodically adds instances if the desired cluster size is less than the current cluster size. Nodes that are detected as idle will be removed only if the current cluster size is greater than the desired cluster size.

Option: There is the possibility of some lower than required number of nodes being added and those nodes being divided among multiple pending, per-sample Spark sub-clusters. Neither of these sub-clusters would be complete and the new nodes would sit idle. To fix this, each Toil job that allocates additional nodes in the above manner should block until its nodes become available. To do so, it loops over the entries in the mapping in the lexicographical order of the keys, summing the values until it hits its own entry in the mapping. If, at that time, it detects that the running sum is less than the current cluster size, it schedules its children. Otherwise it sleeps and retries. The current cluster size is a globally visible value maintained by the überscript, probably another row in the same SimpleDB domain that contains the mapping. This option is the only reason that we need a complex mapping and not just a scalar representing the desired cluster size. The deterministic ordering of the iteration avoids having to track a mapping between individual nodes and samples while still being able to arbitrate between multiple blocked jobs.

Problems: Doesn't model multiple subclusters per sample but maybe we don't need that.

**Comment by almussel** [comment]
The initial draft of this is at: https://github.com/almussel/ADAM-Pipeline-Uberscript . It still contains stubs.

**Comment by almussel** [comment]
PR for this at #114
