### ISSUE TITLE
Batch alignment pipeline throws spurious error if bucket is private

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#103]
If the batch alignment pipeline tries to download FASTQs from a bucket that is private, the download gives something like:

```
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
```

We don't check for this redirect, so we try to align this "FASTQ" file, which gives hilarious (?) error messages.

**Comment by hannes-ucsc** [comment]
Is it because the bucket is private, or because the bucket is in another region. If you use boto's connect_to_region() method, it will not follow these redirects. If you use the S3Connection() constructor, it will. But then you get hit with the redirect for every request. In s3am, I use S3Connection() to determine the bucket's location (same as region, except that region `"us-east-1"` is location `""`) and then connect to the bucket's region via connect_to_region().

**Comment by fnothaft** [comment]
@hannes-ucsc we're using `curl` to download the files right now, and it is because the item in the bucket is private.

**Comment by hannes-ucsc** [comment]
Probably better to use boto to download the file. It's a three liner.

**Comment by fnothaft** [comment]
Strongly agree; we just need someone with the bandwidth to do it.
