### ISSUE TITLE
Function 'docker_call' in toil-scripts library 'programs' missing sudo option

### ISSUE THREAD

**Issue by cmarkello** [BD2KGenomics/toil-scripts#331]

**Comment by cmarkello** [comment]
I'm assigning this to you John because you last touched this file.

**Comment by hannes-ucsc** [comment]
AFAICT, removal of sudo was intentional. The user invoking the docker client indirectly through the Toil script  should be in the `docker` group. That avoids the need for sudo.

**Comment by fnothaft** [comment]
Yeah, I think though that this gets at a good question. How prescriptive do we want to be about how users configure their cluster? I like removing the `sudo` option because it makes _everything so much cleaner_, but it makes the assumption that people set up their clusters so that Docker can be run without sudo.

However, to argue with myself, having docker as a dependency is prescriptive in and of itself. Also, it is less of an ask to ask the user to properly configure their system permissions so that they don't need `sudo` to run docker, than to ask sysadmins everywhere to allow people to "abuse" sudo. Anyways, if you _have_ sudo access, you can just set up the groups properly anyways so that you don't need to run docker as root, which I suppose makes this a bit moot.

@hannes-ucsc @jvivian is this the general reasoning? Apologies for the word vomit.

**Comment by hannes-ucsc** [comment]
Generally agree. But sudo might be limited to just the `docker` binary. Then again, you can

just `sudo docker run -itv /:/x ubuntu vi /x/etc/sudoers`

That's the part about docker that cracks me up.

**Comment by fnothaft** [comment]
> just `sudo docker run -itv /:/x ubuntu vi /x/etc/sudoers`
>
> That's the part about docker that cracks me up.

Or as they often ask, "WHERE IS YOUR GOD NOW‽"

**Comment by jvivian** [comment]
>  I like removing the sudo option because it makes everything so much cleaner, but it makes the assumption that people set up their clusters so that Docker can be run without sudo.

If you have sudo privileges, running Docker without sudo is moot as you can just add yourself to the usergroup.

> Also, it is less of an ask to ask the user to properly configure their system permissions so that they don't need sudo to run docker, than to ask sysadmins everywhere to allow people to "abuse" sudo.

Agreed.

> just sudo docker run -itv /:/x ubuntu vi /x/etc/sudoers
That's the part about docker that cracks me up.
Or as they often ask, "WHERE IS YOUR GOD NOW‽"

I didn't even know you could limit sudo to specific binaries, that's hilarious. 

@cmarkello — Is there a use case preventing you from running toil pipelines where you need `sudo`? If not, I'll go ahead and close this.

**Comment by jvivian** [comment]
I discussed this with @cmarkello and resolved his use case so I'll be closing this.
