### ISSUE TITLE
Rewrite provenance section in Melissa spec

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#43]

**Comment by melissacline** [comment]
See https://docs.google.com/document/d/1i3cGCGfGa4bnNPuW69r8WbF9ON2fM7kZvhSOKBS7xac/edit, item #4 under Inputs

**Comment by jvivian** [comment]
ucsc_cgl tools all have hardcoded tags in this pipeline, so their version is consistent with the git commit hash.  I believe that's all that's necessary to ensure reproducibility.  I didn't include things like Toil version, because that should never have an effect on the output of a pipeline (besides failing to produce an output at all).
