### ISSUE TITLE
Error Messages from BWAkit Invocations are not retained in worker.log

### ISSUE THREAD

**Issue by alex-hancock** [BD2KGenomics/toil-scripts#432]
Hannes will explain. Error message:
```ERROR: failed to locate the BWA index. Please run '/opt/bwa.kit/bwa index -p /data/ref.fa ref.fa'.```

**Comment by hannes-ucsc** [comment]
So it seems that BWA (or our bwa image) does not always return a non-zero status code in error conditions, for example when it can't find  the reference index. We got the error message above when running the docker container for BWA manually without having index files present on disk. The exit code was 0. 

Talking to @alex-hancock and @jvivian made me realize that we already handle cases like this because the job function would fail soon after the BWA invocation, trying to upload a non-existent output file. Closing.
