### ISSUE TITLE
Wig output from STAR for the GTEx runs

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/toil-scripts#80]
The genome browser group, which generously shared their GTEx access with us, have a processing request.  When we run STAR on the GTEx data, they'd like us to add a couple steps to generate bigWig coverage files for them.  See https://github.com/guigolab/grape-nf/blob/master/templates/bigwig/STAR-NONE.  Is this reasonable?

**Comment by Jeltje** [comment]
Bigwigs are generally not that large - the 50 or so I created some time ago range from 15-354K.
The bedGraphs that are used to create them can be quite large (they're uncompressed chromosome coordinate files - chr, chrStart, chrEnd, value) but those are temporary files in this case.

**Comment by jvivian** [comment]
Oops, prematurely closed.  I sent the group a bigwig sample, but this ticket pertains to all samples.

**Comment by jvivian** [comment]
Big recompute is finished! 99.95% of all initial GTEx  samples produced wiggle files.

**Comment by benbfly** [comment]
Are these bigWigs publicly available?
Thanks! Ben.

**Comment by jvivian** [comment]
Hi @benbfly,  We no longer have access to the account where these GTEx big wigs were initially stored, but I handed them all off to Kate Rosenbloom, member of the Genome Browser team, who is (or has) integrated them as tracks in the Genome Browser.  You can email her: kate@soe.ucsc.edu , to see if she can redistribute them to you.  If she can't, please let me know and we'll see if we can work something out.

**Comment by katerose** [comment]
Sorry these aren't available for distribution from UCSC due to identifiability concerns.  You can visualize them from the UCSC genome browser, but downloads are disabled.

There was discussion at the GTEx data coordination center about providing de-identified datasets for public use, but I haven't heard if there is an action plan.   If you are interested in contacting them to inquire, here's a link:

https://www.gtexportal.org/home/contact
